# Generated by Django 3.2.24 on 2024-02-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsysapp', '0002_auto_20240209_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='response_text',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
