# Generated by Django 3.2.24 on 2024-02-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsysapp', '0003_auto_20240212_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fresponse_text',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
