# Generated by Django 3.2.24 on 2024-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsysapp', '0004_feedback_fresponse_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
