# Generated by Django 3.2.24 on 2024-02-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsysapp', '0007_auto_20240212_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='firstname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
