# Generated by Django 3.2.24 on 2024-02-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsysapp', '0010_auto_20240212_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='login',
            name='phone',
        ),
    ]
