# Generated by Django 3.2.24 on 2024-02-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsysapp', '0012_auto_20240212_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(max_length=58),
        ),
    ]
