# Generated by Django 3.2.24 on 2024-02-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingsysapp', '0013_alter_login_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='response_text',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
